name: Build Acropalypse

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install Nuitka
      run: |
        python -m pip install --upgrade pip
        pip install nuitka
        pip install -r requirements.txt

    - name: Build Executable with Nuitka
      uses: Nuitka/Nuitka-Action@main
      with:
         nuitka-version: main
         script-name: gui.py
         onefile: true
         windows-uac-admin: true
         output-file: ${{ matrix.os == 'windows-latest' && 'Acropalypse-Multi-Tool.exe' || 'Acropalypse-Multi-Tool' }}

    - name: Zip Built Files
      run: |
        zip -r Acropalypse-Multi-Tool-${{ matrix.os }}.zip gui.dist/*

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ runner.os }} Build
        path: Acropalypse-Multi-Tool-${{ matrix.os }}.zip
